CREATE TABLE kyc_application_forms (
    application_id TEXT NOT NULL PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    name TEXT,
    date_of_birth TEXT,
    country TEXT,
    nationality TEXT,
    email TEXT,
    phone TEXT,
    consent_confirmed INTEGER NOT NULL DEFAULT 0 CHECK (consent_confirmed IN (0, 1)),
    document_type TEXT,
    document_number TEXT,
    document_country TEXT,
    expiry TEXT,
    street TEXT,
    city TEXT,
    postal TEXT,
    residential_country TEXT,
    document_evidence_present INTEGER NOT NULL DEFAULT 0 CHECK (document_evidence_present IN (0, 1)),
    document_storage_key TEXT,
    document_media_type TEXT,
    document_size INTEGER,
    document_digest TEXT,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (application_id) REFERENCES kyc_applications (id) ON DELETE CASCADE
);
